# SEABORN WORK NOTEBOOK
---
### Where i will be showcasing my work in seaborn i would be taking a data generated by api which deals with weather related stuff i would not be publishing .env file contain api code including api key due to obvious reason

> This is api link https://meteostat.p.rapidapi.com/point/monthly used to generate weather data set!

this code is also present at my kaggle profile : https://www.kaggle.com/thedhawalpanchamiya 

If someone feels to use it you make use it by


```
Install dependencies as needed:
pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

Set the path to the file you'd like to load
file_path = ""

 Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "thedhawalpanchamiya/weather-data-set",
  file_path,
   Provide any additional arguments like 
   sql_query or pandas_kwargs. See the 
   documenation for more information:
  https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

> It contains weather report of coordinates "lat":"52.5244","lon":"13.4105" from date jan - 2020 to dec - 2025

---

### Lets start with importing lib needed

In [39]:
import numpy as np
import pandas as pd 
import seaborn as sns
import scipy as spy
import sklearn as skl

---

### After importing Lib, Now lets load data in dataframe

In [33]:
data = pd.read_csv("weather_data.csv")
data.head()

         date  tavg  tmin  tmax  prcp  wspd    pres   tsun
0  2020-01-01   4.6   2.4   6.8  49.0   NaN  1021.1   3678
1  2020-02-01   6.3   4.0   8.6  89.2   NaN  1010.0   2820
2  2020-03-01   5.7   2.1   9.5  47.6   NaN  1017.8   9966
3  2020-04-01  10.7   5.2  16.3   7.7   NaN  1018.4  17754
4  2020-05-01  12.3   7.3  16.7  26.9   NaN  1019.3  13554

---

### Lets have a quick look at data if needeed we will be dealing be preprocessing as well

In [34]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    72 non-null     str
 1   tavg    72 non-null     float64
 2   tmin    72 non-null     float64
 3   tmax    72 non-null     float64
 4   prcp    72 non-null     float64
 5   wspd    0 non-null      float64
 6   pres    72 non-null     float64
 7   tsun    72 non-null     int64
dtypes: float64(6), int64(1), str(1)
memory usage: 4.6 KB

In this data we have one complete column thats empty we can remove it

In [37]:
data = data.drop(columns = ["wspd"])

In [38]:
data.head()

         date  tavg  tmin  tmax  prcp    pres   tsun
0  2020-01-01   4.6   2.4   6.8  49.0  1021.1   3678
1  2020-02-01   6.3   4.0   8.6  89.2  1010.0   2820
2  2020-03-01   5.7   2.1   9.5  47.6  1017.8   9966
3  2020-04-01  10.7   5.2  16.3   7.7  1018.4  17754
4  2020-05-01  12.3   7.3  16.7  26.9  1019.3  13554

so we have succesfully removed wspd from this data

### Preprocessing

In [41]:
from sklearn.preprocessing import RobustScaler